name: Deploy API Service

on:
  # 推送时执行
  push:
    branches: [main, master]
  # pr 时执行
  pull_request:
    branches: [main, master]
  # 可手动执行
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1、检出源码
      - name: Checkout
        uses: actions/checkout@master
      # 2、安装 Java 环境
      - name: Install Java
        uses: actions/setup-java@master
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'
      # 3、打包
      - name: Build
        run: mvn -B package -DskipTests=true -P prod --file pom.xml
      # 4、拷贝 jar 包到服务器
      - name: Copy Jar
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local: target/charles7c-api.jar
          remote: /docker/charles7c-api/charles7c-api.jar
      # 5、启动
      - name: Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /docker
            docker stop charles7c-api && docker rm charles7c-api
            docker rmi docker_charles7c-api
            docker-compose up charles7c-api -d